package rafael.ktgenetic

enum class ProcessorEventEnum {
    STARTING,
    FIRST_GENERATION_CREATING,
    FIRST_GENERATION_CREATED,

    GENERATION_EVALUATING,
    FITNESS_CALCULATING,
    FITNESS_CALCULATED,
    SELECTING,
    SELECTED,
    REPRODUCING,
    REPRODUCED,
    GENERATE,
    GENERATION_EVALUATED,

    ENDED_BY_GENERATIONS,
    ENDED_BY_FITNESS
}